[build]
command = "npm run build"
publish = "build/client"

[build.environment]
NODE_VERSION = "24"

[[redirects]]
from = "https://slugify-me.netlify.app/*"
to = "https://slugify.me/:splat"
status = 301
force = true

[[redirects]]
from = "/*"
to = "/__spa-fallback.html"
status = 200
