import { describe, it } from 'vitest';
import { expectStableSlug } from './slugify.test-helpers';

describe('English vocabulary and notation', () => {
	const termCases = [
		['F# programming', 'f-sharp-programming'],
		['Notepad++', 'notepad-plus-plus'],
		['g++ compiler', 'g-plus-plus-compiler'],
		['clang++', 'clang-plus-plus'],
		['libstdc++', 'libstdc-plus-plus'],
		['libc++', 'libc-plus-plus'],
		['GTK+', 'gtk-plus'],
		['.NET 8', 'dot-net-8'],
		['ASP.NET Core', 'asp-net-core'],
		['VB.NET', 'vb-net'],
		['C++/CLI', 'cpp-cli'],
		['C++98', 'cpp-98'],
		['C++03', 'cpp-03'],
		['C++11', 'cpp-11'],
		['C++14', 'cpp-14'],
		['C++17', 'cpp-17'],
		['C++20', 'cpp-20'],
		['C++23', 'cpp-23'],
		['C++26', 'cpp-26'],
		['D* Lite', 'd-star-lite'],
		['D* algorithm', 'd-star-algorithm'],
		['IDA* search', 'ida-star-search'],
		['LPA* algorithm', 'lpa-star-algorithm'],
		['RRT* planner', 'rrt-star-planner'],
		['C*-algebra', 'c-star-algebra'],
		['C* algebras', 'c-star-algebras'],
		['W*-algebras', 'w-star-algebras'],
		['B* algebra', 'b-star-algebra'],
		['B+-tree', 'b-plus-tree'],
		['B+ trees', 'b-plus-trees'],
		['B*-trees', 'b-star-trees'],
		['B* tree', 'b-star-tree'],
		['LGBT+ history', 'lgbt-plus-history'],
		['LGBTQ+ rights', 'lgbtq-plus-rights'],
		['LGBTQIA+ history', 'lgbtqia-plus-history'],
		['Disney+ shows', 'disney-plus-shows'],
		['Paramount+', 'paramount-plus'],
		['Apple TV+', 'apple-tv-plus'],
	] as const;

	it.each(termCases)('preserves the meaning of %j', (input, expected) => {
		for (const spelling of [
			input,
			input.toLowerCase(),
			input.toUpperCase(),
		]) {
			expectStableSlug(spelling, expected);
			expectStableSlug(`(${spelling}),`, expected);
			expectStableSlug(
				`${spelling}; ${spelling}`,
				`${expected}-${expected}`,
			);
		}
	});

	it.each([
		['The best books - a guide', 'the-best-books-a-guide'],
		['Hello - world', 'hello-world'],
		['Hello – world', 'hello-world'],
		['Hello — world', 'hello-world'],
		['word - word - word', 'word-word-word'],
		['and / or', 'and-or'],
		['he / she', 'he-she'],
		['input / output', 'input-output'],
		['input/output', 'input-output'],
		['yes / no / maybe', 'yes-no-maybe'],
		['R&B music', 'r-and-b-music'],
		['Q&A', 'q-and-a'],
		['24/7 support', '24-7-support'],
		['24 / 7 service', '24-7-service'],
		['9/11 memorial', '9-11-memorial'],
		['4/4 time', '4-4-time'],
		['6 / 8 meter', '6-8-meter'],
		['a / b', 'a-divided-by-b'],
		['x - y', 'x-minus-y'],
		['2 - 1', '2-minus-1'],
		['24/7', '24-divided-by-7'],
		['9/11', '9-divided-by-11'],
		['24/7=3', '24-divided-by-7-equals-3'],
		['foo2 / bar3', 'foo2-divided-by-bar3'],
		['co-operate', 'co-operate'],
		['re-sign', 're-sign'],
		['mother-in-law', 'mother-in-law'],
		['jack-o’-lantern', 'jack-o-lantern'],
		['will-o’-the-wisp', 'will-o-the-wisp'],
		['donʼt', 'dont'],
		['OʼNeill', 'oneill'],
		['maʼam', 'maam'],
		['co\u00adoperate', 'cooperate'],
		['encyclopædia', 'encyclopædia'],
		['œuvre', 'œuvre'],
		['naïveté', 'naivete'],
		['coöperation', 'cooperation'],
		['Schrödinger’s cat', 'schrodingers-cat'],
		['Gödel’s theorem', 'godels-theorem'],
		['Möbius strip', 'mobius-strip'],
		['fin-de-siècle', 'fin-de-siecle'],
		['l’esprit de l’escalier', 'lesprit-de-lescalier'],
		['A+ student', 'a-plus-student'],
		['B- grade', 'b-minus-grade'],
		['AB+ blood', 'ab-positive-blood'],
		['AB- blood', 'ab-negative-blood'],
		['O− blood', 'o-negative-blood'],
		['Rh+ donor', 'rh-positive-donor'],
		['18+', '18-plus'],
		['65+ discounts', '65-plus-discounts'],
		['30+ recipes', '30-plus-recipes'],
		['A+ B', 'a-b'],
		['5+ x', '5-x'],
		['5+2', '5-plus-2'],
		['5 + 2', '5-plus-2'],
		['5++', '5-increment'],
		['myF#', 'myf'],
		['F#oo', 'f-oo'],
		['中F#文', '中f-文'],
		['myNotepad++', 'mynotepad-increment'],
		['Notepad++foo', 'notepad-foo'],
		['C*algebraic', 'c-times-algebraic'],
		['RRT*value', 'rrt-times-value'],
		['C*D', 'c-times-d'],
		['B+C', 'b-plus-c'],
		['*grade A*', 'grade-a'],
		['https://example.com/B♭?q=18+', 'https-example-com-b-q-18'],
	] as const)('distinguishes English context in %j', (input, expected) => {
		expectStableSlug(input, expected);
	});

	for (const note of ['A', 'B', 'C', 'D', 'E', 'F', 'G']) {
		for (const [symbol, word] of [
			['♯', 'sharp'],
			['♭', 'flat'],
			['♮', 'natural'],
			['𝄪', 'double-sharp'],
			['𝄫', 'double-flat'],
		]) {
			it(`preserves the ${note}${symbol} musical accidental`, () => {
				expectStableSlug(
					`${note}${symbol} minor`,
					`${note.toLowerCase()}-${word}-minor`,
				);
				expectStableSlug(
					`${note}${symbol}4`,
					`${note.toLowerCase()}-${word}-4`,
				);
			});
		}
	}

	it.each([
		['D# major', 'd-sharp-major'],
		['F# minor', 'f-sharp-minor'],
		['C#1', 'c-1'],
		['½ cup', 'one-half-cup'],
		['1½ cups', '1-and-one-half-cups'],
		['1 1/2 cups', '1-and-one-half-cups'],
		['1/2 cup', 'one-half-cup'],
		['1⁄2 cup', 'one-half-cup'],
		['1 1⁄2 cups', '1-and-one-half-cups'],
		['https://example.com/½', 'https-example-com-1-2'],
		['HTTPS://example.com/?x≮y', 'https-example-com-x-y'],
		[
			'*https://example.com/½* 1½ cups',
			'https-example-com-1-2-1-and-one-half-cups',
		],
		['5/16-inch', '5-over-16-inch'],
		['.5 cup', '0-point-5-cup'],
		['1/2', '1-divided-by-2'],
		['1/0 cups', '1-divided-by-0-cups'],
		['2026/9/2 cups', '2026-9-2-cups'],
		['11½ inches', '11-and-one-half-inches'],
		['2⅔ cups', '2-and-two-thirds-cups'],
		['⅛-inch', 'one-eighth-inch'],
		['⅞ inch', 'seven-eighths-inch'],
		['⅐', 'one-seventh'],
		['⅑', 'one-ninth'],
		['⅒', 'one-tenth'],
		['⅓', 'one-third'],
		['⅕', 'one-fifth'],
		['⅖', 'two-fifths'],
		['⅗', 'three-fifths'],
		['⅘', 'four-fifths'],
		['⅙', 'one-sixth'],
		['⅚', 'five-sixths'],
		['⅜', 'three-eighths'],
		['⅝', 'five-eighths'],
		['¼', 'one-quarter'],
		['¾', 'three-quarters'],
		['20°C', '20-degrees-celsius'],
		['20℃', '20-degrees-celsius'],
		['68°F', '68-degrees-fahrenheit'],
		['68℉', '68-degrees-fahrenheit'],
		['1 °C', '1-degree-celsius'],
		['−5°C', 'negative-5-degrees-celsius'],
		['Temperature −5°C', 'temperature-negative-5-degrees-celsius'],
		['Temperature -5°C', 'temperature-negative-5-degrees-celsius'],
		['10×5', '10-times-5'],
		['10 ÷ 5', '10-divided-by-5'],
		['10−5', '10-minus-5'],
		['x ≠ y', 'x-not-equals-y'],
		['x =\u0338 y', 'x-not-equals-y'],
		['x ≮ y', 'x-not-less-than-y'],
		['x <\u0338 y', 'x-not-less-than-y'],
		['x ≯ y', 'x-not-greater-than-y'],
		['x ≰ y', 'x-not-less-than-or-equal-to-y'],
		['x ≤\u0338 y', 'x-not-less-than-or-equal-to-y'],
		['x ≱ y', 'x-not-greater-than-or-equal-to-y'],
		['x ≥\u0338 y', 'x-not-greater-than-or-equal-to-y'],
		['x ≤ 5', 'x-less-than-or-equal-to-5'],
		['x ≥ 5', 'x-greater-than-or-equal-to-5'],
		['5 ± 2', '5-plus-or-minus-2'],
		['±5%', 'plus-or-minus-5-percent'],
		['≠ ≮ ≯ ≤ ≥ × ÷ ± −', ''],
	] as const)(
		'preserves numeric and Unicode meaning in %j',
		(input, expected) => {
			expectStableSlug(input, expected);
		},
	);

	it.each([
		'about',
		'after',
		'before',
		'between',
		'book',
		'business',
		'child',
		'computer',
		'different',
		'education',
		'example',
		'family',
		'friend',
		'government',
		'health',
		'history',
		'home',
		'information',
		'language',
		'people',
		'question',
		'school',
		'science',
		'through',
		'time',
		'water',
		'world',
		'abecedarian',
		'absquatulate',
		'agathokakological',
		'borborygmus',
		'cwm',
		'defenestration',
		'epicaricacy',
		'floccinaucinihilipilification',
		'kakistocracy',
		'logomachy',
		'nudiustertian',
		'obstreperous',
		'opsimath',
		'quincunx',
		'sesquipedalian',
		'synecdoche',
		'syzygy',
		'tmesis',
		'ultracrepidarian',
		'uxorious',
		'velleity',
		'zeugma',
		'zwitterion',
		'pneumonoultramicroscopicsilicovolcanoconiosis',
	])('preserves the English word %s in titles and compounds', (word) => {
		expectStableSlug(
			`Learn ${word.toUpperCase()} today!`,
			`learn-${word}-today`,
		);
		expectStableSlug(`pre-${word}-post`, `pre-${word}-post`);
		expectStableSlug(`(${word}),`, word);
	});
});
